### ISSUE TITLE
Update plot squared using a command like /plot update

### ISSUE THREAD

**Issue by johncsuti** [IntellectualSites/PlotSquaredSuggestions#100]
**PlotSquared Feature Suggestion:**

Also console to run a command to download and install the updated version of the plugin without having to use a file transfer program

**How should it be implemented?**

Pretty self explanatory

**Additional context**

Nope I know some plugins already do this

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
Due PlotSquared v5 being treated as premium plugin, an auto updater will not work unless you have some sort of authentication token/creds on your server/machine you can use to log in to your spigot account and download anything from that.
While typing this, I can already come up with a few vulnerabilities someone can easily abuse to perform malicious actions with your account/the server, nevertheless some hosting services seem to block things like that like they have told us in the past when we were using auto updaters.
