### ISSUE TITLE
Restricting WorldEdit selection to within a plot

### ISSUE THREAD

**Issue by Hypermoron** [IntellectualSites/PlotSquaredSuggestions#101]
**PlotSquared Feature Suggestion:**
When WorldEdit is restricted to plots, selection operations should only work inside of plots.

**How should it be implemented?**
With _worldedit-restrictions_ set to _true,_ any player without bypass enabled will receive an error when attempting to select a region that extends past any border of a plot they have access to. The selection will not be created/changed. This is the case no matter by what means the selection is created.

Alternatively, any operations on a selection larger than the plot should be canceled.

Perhaps a new boolean in config like _restrict-selections_ should be added, to allow admins the option to let players run worldedit copy/analysis operations on others' claims.

**Additional context**
WorldEdit and PlotSquared do well at setting constraints on edits, but server admins still need to be careful about granting players access to selection commands. A sufficiently large selection can be used to crash a server using commands like //distr and //copy.

**Checklist**:
- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
WorldEdit is restricted to the plot by default unless explicit bypass permissions are granted. You cannot set something outside the plot unless you have the permission to do so.

**Comment by RedstoneFuture** [comment]
![2020-07-29_15 23 16](https://user-images.githubusercontent.com/4140635/88805457-74f64500-d1af-11ea-9f4a-8884ccc7169f.png)

"Alternatively, any operations on a selection larger than the plot should be canceled." It seems like a "cancel".
