### ISSUE TITLE
Option to make it so you must be trusted to use worldedit

### ISSUE THREAD

**Issue by DoogiePC** [IntellectualSites/PlotSquaredSuggestions#105]
**PlotSquared Feature Suggestion:**
Old plotsquared behaviour made it so added players could NOT use worldedit on someones plot. To use worldedit they had to be trusted. I wish for it to be an option to enable or just default behaviour again.

**How should it be implemented?**
To limit griefs where possible.

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by dordsor21** [comment]
This exists, do not give players fawe.plotsquared.member
