### ISSUE TITLE
Flag Placeholders

### ISSUE THREAD

**Issue by SnoopyDevAU** [IntellectualSites/PlotSquaredSuggestions#106]
**PlotSquared Feature Suggestion:**

A boolean placeholder for each plot flag.

**How should it be implemented?**

So, for example if the "vehicle-use" flag is enabled on a plot then the placeholder will return "true". And to allow for even more customization allow users to edit what each true/false placeholder returns in a configuration, so instead of "true" it displays "enabled" instead for example.

This will allow server owners to create a nice GUI to allow their users to see and modify their plot settings through that instead of typing commands.

**Additional context**

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
I think for this GUI a plotsquared add-on must work with the API. I like the idea, but I see problem with the many non-boolean placeholders.

**Comment by RedstoneFuture** [comment]
Maybe `{plotsquared_<flag>}`.

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/122

**Comment by SnoopyDevAU** [comment]
Yeah, {plotsquared_<flag>} would be fine.

**Comment by RedstoneFuture** [comment]
At now we have 2 new flags:


`%plotsquared_currentplot_localflag_<flag>%`
= Display the value of the flag set on current plot

`%plotsquared_currentplot_flag_<flag>%`
= Display the value of the flag set on current plot or if it's not set: display the inherited flag value (worlds.yml)
