### ISSUE TITLE
Plot Rollback

### ISSUE THREAD

**Issue by TheRobLP** [IntellectualSites/PlotSquaredSuggestions#107]
**PlotSquared Feature Suggestion:**
A configurable, new option in the config which will save Plot states each x amount of time, so if something goes wrong, for example data loss admins can restore one plot, or the whole world.

**How should it be implemented?**
There would be a new config option called "Rollback." It would look like this:

Rollback:
   // I think this one is self-explanatory
   Enabled: false
   // The time before old saved states get deleted. Can be minutes, hours, days, weeks etc.
   Save-History: 12h
   // Boolean which controls if players should be allowed to rollback their own plots
   AllowEveryone: false
   // Boolean which will ask the user to confirm the action via /plots confirm, if true
   ConfirmRollback: true

There will be one new sub-command ingame for this:

/plots rollback [world/plot] [RollbackTime] {WhatToRollback}

world/plot : The variable world, will result in a rollback of the entire world to a previous version.   
                    The variable plot, will result in a rollback of the current plot you are standing in.

RollbackTime: The amount of time to rollback to. Example: 1h would rollback to 1 hour ago.

WhatToRollback: Optional variable, where you can specify what exactly should be rolled back. (blocks entities, sepcifc entities/blocks etc.) If left empty a full rollback is applied.

**Additional context**
   An alternative solution would be, to make PlotSquared compatible with the free plugin 
   "CoreProtect" and let it handle most of this, as it already has a solid foundation. Altough Im not 
   sure if their API is able to allow that. 
   https://minerealm.com/community/viewtopic.php?f=32&t=16687

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by dordsor21** [comment]
PlotSquared shouldn't need to be your backup system. There are existing plugins/external-to-minecraft programs to use that will be more effective. You can use //restore from WorldEdit also.
