### ISSUE TITLE
KeepInventory Flag

### ISSUE THREAD

**Issue by Aurelien30000** [IntellectualSites/PlotSquaredSuggestions#108]
**PlotSquared Feature Suggestion:**

Hey ! Would be great if you could add a (boolean) flag to keep inventory or not, after a death in a plot.

Thanks :)

**How should it be implemented?**

**Simple example:**
/plot flag set keep-inventory true -> When ever a player dies in this plot, he keeps it's inventory and experience.
/plot flag set keep-inventory false -> When ever a player dies in this plot, it's inventory and experience drop or disappear, (with vanilla / default conditions).

**Additional context**

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by Sauilitired** [comment]
Will be present in the next PlotSquared v5 update!
