### ISSUE TITLE
Cancel teleportation when teleporting to plot on which player is denied

### ISSUE THREAD

**Issue by 4Cris** [IntellectualSites/PlotSquaredSuggestions#109]
Would it be possible to not do the teleportation at all when a player teleports himself to a plot on which he is denied. With the actual situation, players can bug themselves through blocks which isn't really great on community plots where players only have limited access.

Thanks in advance

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/092690e9f00ae3543c2468c844de12d692cfe33f
