### ISSUE TITLE
limit plot members

### ISSUE THREAD

**Issue by soulstriker23** [IntellectualSites/PlotSquaredSuggestions#110]
**PlotSquared Feature Suggestion:**
When adding members, have a section to add permissions to limit how many people they can invite/add on their plot. Works with both members and trusted.

**How should it be implemented?**
Permissions: "plots.add.member.<#>" - which will limit the number of members allowed on the plot
Permissions: "plots.add.trusted.<#>" - which will limit the number of trusted allowed on the plot

**Or**
Permissions: "plots.add.total.<#>" - which will limit the number of people allowed on the plot. Accounts for both members & trusted.

Say an owner of the plot has "plots.add.member.2" - they can only have 2 active members. - they could trust these members to trusted, but they only able to have 1 trusted "trusted plots.add.trusted.1". So total of people allowed on the plot is 3. 

First method could get complicated, so maybe having total amount is best?
Owner of plot has "plots.add.total.5" > only allowed 5 total people in the plot, includes members/trusted.

Owner of plot has "plots.add.total.0" > no members are allowed to be invited.

**Additional context**
This can be helpful for if you are having build competitions, or have team comp and you need to limit number of members/trusted allowed in a plot.

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
Or a player have a limit-permission to get the "member" / "trusted" rank. In this solution it's not based on the owner-permission, but based on the new player to get this "member" / "trust" rank. The same logic as "plot.plots.<x>".


What's better?
