### ISSUE TITLE
Custom music on plots

### ISSUE THREAD

**Issue by Th4tM0nk3y** [IntellectualSites/PlotSquaredSuggestions#111]
**PlotSquared Feature Suggestion:**
Being abe to add and listen to  custom music through /p music
**How should it be implemented?**
There are two ways I could think of:
1. have a folder of music on the server which then can be filled with music by the server ops, or 
2. use a system to call stuff from e.g. YT.

Would be great if this could make it into the plugin, I really like it.

Cheers,
Th4tM0nk3y

**Comment by MattBDev** [comment]
I'm not sure if this is possible without a modded client but I'd really like to look into this.

**Comment by dordsor21** [comment]
You can add a custom resource pack that overrides the vanilla music and prompt players to download on join, but otherwise, it's not possible.
