### ISSUE TITLE
Multiple player setowner

### ISSUE THREAD

**Issue by nirewen** [IntellectualSites/PlotSquaredSuggestions#113]
**PlotSquared Feature Suggestion:**

**How should it be implemented?**

As of right now, a plot can hold many owners if you merge a plot with another player's plot.

The command `/plot setowner` sets the owner of the plot, but it doesn't allow more than 1 argument, meaning it only sets a single owner for the plot.

That's not very fortunate when you want to change the owners of the plot. 
You would have to ask the current owners which one would want to be the definitive owner of the plot.

Say the owners of plot `1;1` are jeb_, JohnDoe and Notch. I want to remove Notch from the owners list, but keep JohnDoe and jeb_. Or I want to add SomeoneElse to the list without removing anyone.
So I could do `/plot setowner jeb_ JohnDoe` to remove Notch.
And `/plot setowner jeb_ JohnDoe Notch SomeoneElse` to keep Notch and add SomeoneElse.

Final command syntax: `/plot setowner <player> [...players]`

**Additional context**

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
I think you get many problems with the plugin mechanics (plot list, flag toggle, API problems, plot sign etc.) if you add support for a multi-player "owner" plot-group.

Furthermore, I see problems with the server rules if you haven't one responsible person.

**Comment by xManInWhitex** [comment]
If two players merging their plots, there are multiple owners at one plot. So I think this might be possible.

**Comment by AeSix** [comment]
just re-iterating my belief that polyownership should not be allowed, or should be handled appropriately throughout the whole of PlotSquared.

**Comment by RedstoneFuture** [comment]
> 
> 
> just re-iterating my belief that polyownership should not be allowed, or should be handled appropriately throughout the whole of PlotSquared.

Same. Currently, it's possible to get multi-owner, but it's a bug.

**Comment by N0tMyFaultOG** [comment]
Won't be added.
