### ISSUE TITLE
Insertion of flag values

### ISSUE THREAD

**Issue by nirewen** [IntellectualSites/PlotSquaredSuggestions#115]
**PlotSquared Feature Suggestion:**

**How should it be implemented?**

When checking for the plot's flag list (using `/plot flag list`) you could be able to insert a flag's value into the chat.
When using the `use` flag, things can get very long and would be very tiring to retype to add a new block to the list. So, Shift+Click the flag value to insert to your already typed `/plot flag set use ` message.

How to implement:
`insertion` is a key in the JSON, it only accepts a string of text.
`{..., "insertion": "flag values", ...}`
or using `net.md_5.bungee.api.chat.BaseComponent`:
`component.setInsertion("flag values");`
Reference: https://minecraft.gamepedia.com/Raw_JSON_text_format

Additionally, flag values could be autocompleted aswell when setting them.

**Additional context**

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by SirYwell** [comment]
You can use `/plot flag add use <more types>`, that's better than inserting all of the already set values into the chat.

**Comment by Sauilitired** [comment]
This won't be added. As @SirYwell pointed out, flag values can already be added to list flags by using `add` rather than `set`.
