### ISSUE TITLE
/plot clear empties chests before clearing chunk

### ISSUE THREAD

**Issue by james090500** [IntellectualSites/PlotSquaredSuggestions#117]
Using ``/plot clear`` decides to empty chests before clearing the plot. This is a massive issue and crashed our server when trying to clear an old plot

![image](https://user-images.githubusercontent.com/20372645/81844821-9009cf00-9547-11ea-89de-0a99600e5267.png)

**Comment by Orlaando-dev** [comment]
You put this in PlotSquaredSuggestions. Report this issue on the PlotSquared repository.

**Comment by james090500** [comment]
Oops! I have no idea how I managed to do that. I will move it there.
