### ISSUE TITLE
add wiki for mvmplaceholders

### ISSUE THREAD

**Issue by leoncp9** [IntellectualSites/PlotSquaredSuggestions#118]
i see placeholders for featherboard at plotsuared 5
https://wiki.intellectualsites.com/plotsquared/placeholders
they don't work
like {plotsquared_plot_count}
where are th wiki of the mvmplaceholders list

**Comment by Sauilitired** [comment]
![image](https://i.imgur.com/YV4jKOi.png)

We only support PlaceholderAPI, but you can use that format and it should work.

**Comment by leoncp9** [comment]
{placeholderapi_plotsquared_members}
{placeholderapi_plotsquared__xy}
this two placeholders don't show nothing at featherboard plugin
proof:
https://prnt.sc/sin4nh

**Comment by Sauilitired** [comment]
Those are not valid placeholders. Take another look at the wiki.
