### ISSUE TITLE
Offer pet (and other similar) plugins the ability to stop P2 from doing stuff with their entities (through tags/metadata)

### ISSUE THREAD

**Issue by ofunny** [IntellectualSites/PlotSquaredSuggestions#119]
**PlotSquared Feature Suggestion:**
Make PlotSquared compatible with GadgetsMenus animals.

**How should it be implemented?**
GadgetsMenu exists as free and as premium version, it is one of the best cosmetic plugins for Spigot and Paper.

With GadgetsMenu you can get any Mob (hostile to animals) as pet and you can also ride the pets.
There is also a Gadget to ride another player (Cowboy).

People actually really like the feature to ride the pets they got via GadgetsMenu what leads to problems with the awesome PlotSquared plugin.
1. A player who rides a pet in a plot can not get kicked, PS is not finding the player while he rides a pet. Only if he gets off the pet, the player can be kicked.
2. A denied player can enter the plot while riding a pet. If he get of in the plot, he can not move anymore, until he gets up again.
3. This problem with the detection and finding of a player while he ride a pet is a problem in generell.
Would be awesome if it could be fixed.
4. [optional] the function what remove mobs on roads – actually very usefull – will also remove pets. It would be awesome if it could check if a pet is from GadgetsMenu or just a mob.

**Additional context**
Link to the plugin on Spigot
Free: https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-15-free.10885/)
Premium: https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-15-premium.62831/

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
That sounds more like an issue with the GadetsMenu plugin. Plugins like [Miniature Pets](https://www.spigotmc.org/resources/miniature-pets-create-your-personal-companions.23991/) have no issues like that.

**Comment by RedstoneFuture** [comment]
I test point 1 - 3 with normal mobs. Maybe it's a problem with animal riding.

4. Have GadgetsMenu mobs a NBT tag to detect it? @ofunny

**Comment by ofunny** [comment]
I will ask the main developer of GadgetsMenu to answer it.

**Comment by dordsor21** [comment]
Tbh I think it would be better if we had an overall tag that P2 can detect, rather than having to implement one for every single plugin that does stuff with pets, or entities. P2 is one plugin. There are many many many plugins that we are not going to offer support for each individually.

**Comment by dordsor21** [comment]
Actually, will reopen but change title to having the opportunity for other plugins to declare entities as "don't remove"

**Comment by RedstoneFuture** [comment]
My idea was a new list in the config to add a whitelist-nbt tag (specific name or other). Or whatever plugins like GadgetMenu do you do to detect her mobs.

**Comment by RedstoneFuture** [comment]
> 
> 
> I test point 1 - 3 with normal mobs. Maybe it's a problem with animal riding.
> 

It works fine: banned players who are riding are kicked when they ride into the plot.

**Comment by RedstoneFuture** [comment]
Sry

**Comment by OnlyNoobDied** [comment]
This issue will be solved by GadgetsMenu which will be release soon.

**Comment by dordsor21** [comment]
This should be left open so as to make it easier for other plugins in the future. It might make whatever the fix with GadgetsMenu better performing if this is added to P2.

**Comment by OnlyNoobDied** [comment]
For further information, GadgetsMenu does have a NBTTag called "GadgetsMenu".

Removing mobs might be difficult when mob plugin customizing mob and override the kill method. That's why GadgetsMenu pets are not removed when the plot owner execute the remove mob command.
