### ISSUE TITLE
PlaceHolders

### ISSUE THREAD

**Issue by AodX** [IntellectualSites/PlotSquaredSuggestions#12]
Hello,
I would like to suggest that this plugin have Placeholders, ( give it PlaceholderAPI support )
and have stuff like, how many Plots the player have, *for example* {Plot_number}...etc

**Comment by Sauilitired** [comment]
An extension was created by IronApollo, [here](https://github.com/IntellectualSites/PlotSquared-Expansion) is the link :cow:
