### ISSUE TITLE
entity-pathing: mobs can still escape from plots after getting attacked by a player

### ISSUE THREAD

**Issue by ofunny** [IntellectualSites/PlotSquaredSuggestions#121]
**PlotSquared Feature Suggestion:**
Even with entity-pathing: true, all mobs that will follow and attack you (after the player harms them first) will track and follow you out of any plot. Entity-pathing will not work in this circumstance.

**How should it be implemented?**
With entity-pathing on, mobs should not get out of any plot, even if they are in attack mode and track/follow a player. No matter if the player harmed them before or not.

**Additional context**
You can try it out with dogs, cave spider and any other mob that follows you, after you harm it.

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by dordsor21** [comment]
The issue most likely lies with paper. The event they have is not called all the time, and there's not much we can do about it.
