### ISSUE TITLE
Placeholder for PlotSquared Flag

### ISSUE THREAD

**Issue by ProZiomekXDM** [IntellectualSites/PlotSquaredSuggestions#122]
**PlotSquared Feature Suggestion:**

I would like to suggest adding a placeholder to the plugin.

Eg: Player has add /plot flag add use DARK_OAK_DOOR,JUNGLE_DOOR
And checking the flag by PlaceholderAPI: DARK_OAK_DOOR

Add this expansion: %plotsquared_has_plot_flag_#_#% = "true" or "flase"
For example: %plotsquared_has_plot_flag_use_DARK_OAK_DOOR% = true
And if the player removes the flag he will show FALSE

It could be useful for scripts and various types of menus in the GUI.
![20200524_204936](https://user-images.githubusercontent.com/17661300/82762292-629f0a00-9e00-11ea-92c3-932d51f90f55.gif)

**Checklist**:

- [] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
I think only `{plotsquared_<flag>}` would be enough.
