### ISSUE TITLE
permissions list

### ISSUE THREAD

**Issue by Jacielegit** [IntellectualSites/PlotSquaredSuggestions#123]
**PlotSquared Feature Suggestion:**

give us the link of the permission's list
**How should it be implemented?**

by a site
**Additional context**

nan
**Checklist**:

- [ ] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [ ] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
Check on the wiki https://wiki.intellectualsites.com/
