### ISSUE TITLE
Update PlotRankup (PlotRankup + IslandPlots, ...)

### ISSUE THREAD

**Issue by Loonyy** [IntellectualSites/PlotSquaredSuggestions#125]
**PlotSquared Feature Suggestion:**
Hey, I'm just wondering if there's any plans to update the addon plugins, such as PlotRankup and IslandPlots? 

I'd really like PlotRankup.

**Comment by RedstoneFuture** [comment]
Please open an issue with the error at https://github.com/IntellectualSites/PlotRankup and https://github.com/boy0001/IslandPlots/issues .

**Comment by RedstoneFuture** [comment]
@Sauilitired I think we can describe the addons in the new wiki in the future, if these plugins works fine.

**Comment by RedstoneFuture** [comment]
Closed, because this is not a bug.
