### ISSUE TITLE
Allow end user customization of tab complete definitions

### ISSUE THREAD

**Issue by Tarlak333** [IntellectualSites/PlotSquaredSuggestions#126]
**PlotSquared Feature Suggestion:**
This feature would allow the end-user to define the tab complete information for PS commands to work only with user defined PS command aliases.

**How should it be implemented?**
I think this is a fairly straightforward request, presently the tab complete command definitions are hard-coded to a large list of commands that start with /plot.  As of PS v5.11.1 entering /plot on the command line will generate the following list of tab complete options:

plot
plotme
plots
plotsquared
plotsquared:2
plotsquared:p
plotsquared:p2
plotsquared:plot
plotsquared:plotme
plotsquared:plots
plotsquared:plotsquared
plotsquared:ps

This large tab complete listing seems redundant and adds ambiguity to the "preffered" command the server owner would like players to use for PS.  This also conflicts to a degree with other plot plugins that use /plot, that may be concurrently in use. (Ex. Such as on RPG servers that are also using a "survival wilderness" type plot plugin.)

**Note:** Presently PS allows commands to be tied to aliases, many of which are listed above.

I feel it would be beneficial to the PS community to allow the tab complete information to be customized so that it could be tied to a **single** preferred alias.  From the players perspective this would allow for separation of command systems between PS and other plugins that use /plot* type commands.  (Ex.  Remap tab complete to only auto-fill when /p2 is entered not /plot) 
 
**Additional context**
None

**Checklist**:

- [**X**] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [**X**] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [**X**] I made sure my suggestion is useful for the majority of PlotSquared users

I'm not that involved in the community yet, but I feel this feature would allow a greater degree of customization to PS and decrease clutter & command ambiguity which is always a good thing. :)

**Comment by DevJoey** [comment]
That would be a nice feature. I also recommend to remove the /plotme command because PlotSquared is not Plotme! it would be cool if plotsquared only had these commands: /plot /p /plotsquared /p2 /plots

/ps and /plotme a complete useless!

**Comment by N0tMyFaultOG** [comment]
Won't be added.
