### ISSUE TITLE
/plot delete (by player), add option "onDelete teleport to" 

### ISSUE THREAD

**Issue by spaik66** [IntellectualSites/PlotSquaredSuggestions#127]
**PlotSquared Feature Suggestion:**
Start by saying i use the Legacy 1.8-.1.12.2 and iam very pleased, but we really need that.
Generaly on plots like skyblock, seaplots, cannon servers, etc.. After the execcution of </plot delete> the player still staying as long as he wants inside the without ownership plot. Of course can not edit terrain but can make other problems in varius games.

**How should it be implemented?**
By adding 2 easy checkings and 2 lines in config
onDelete_teleportation: (true/false)
destination:[ ] ----> (to lobby, world etc...)

So, when player do "/plot delete" , player freezes, and when message appears "The plot plot-id has been deleted" (deleting time depends on servers_power and plot_size so must stay freezed) , after 1 sec to teleport the player to the specified destination.

**Additional context**

**Checklist**:

- [] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by spaik66** [comment]
Now we use the "/plot dispose" custom command , and took <off> the plot.delete permission from players.
------
/plot dispose  (as_operator)
   commands:
   -/plot home
   -/plot delete
   -/freeze %player% 60sec (by console) (because big plots and busy server, but not always intime)
   - !wait 61sec
   -/tp %player% lobby
---------

**Comment by RedstoneFuture** [comment]
```
By adding 2 easy checkings and 2 lines in config
onDelete_teleportation: (true/false)
```

1. bypass permission for staff user

2. config-option for all worlds with the position (X Y Z, Yaw, Pitch)

3. teleport-messages for the player

4. maybe setpos command

5. onDelete_teleportation: (true/false) for all worlds

6. Teleport only for plot-owner or for all plot-members?

**Comment by spaik66** [comment]
No need all those.. i believe has to be:
-------------------
By adding 2 easy checkings and 2 lines in config
onDelete_teleportation: [] (true/false)
destination:[ ] ----> (to lobby, world etc...)
-----------------------
What it does?
**Config:**
onDelete_teleportation: true
destination: spawn

**Execution**
/plot delete (starts plot deleting + kick all from plot---> because you are the plot owner with the perm)
<message: plot-ID has been deleted>
<message: you are teleported to [spawn]>

**Comment by N0tMyFaultOG** [comment]
Wont be added.
