### ISSUE TITLE
Blocking the use of portals

### ISSUE THREAD

**Issue by JavituRec** [IntellectualSites/PlotSquaredSuggestions#128]
**PlotSquared Feature Suggestion:**
Hi, I'd like to be able to block the use of nether portals in plots. 

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [ ] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
try this: https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#portal-form

**Comment by RedstoneFuture** [comment]
I think, the portal management was not the task for PlotSquared. For example, you can use Multiverse or [Hyperverse](https://www.spigotmc.org/resources/hyperverse-w-i-p.77550/) to change this.

In other case, we need more infos of your problem and the reason to manage this problem with PlotSquared, please.
