### ISSUE TITLE
"deleting_done" message: add placeholder to show the last owner (+ID)

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquaredSuggestions#129]
**PlotSquared Feature Suggestion:**
You use the command "/p delete " If you don't find the plot or this location have a chunk-problem. In this situation the plot-owner name would be interesting.

I can't use the PAPI placeholder to show the owner at here, because in this time the plot was already deleted.

**How should it be implemented?**
Maybe it's a suggestion, but I think we support placeholders in the translation strings:

` deleting_done: $4Delete completed! Took %s ms. --- ID: %s2 | owner: %s3`

**Additional context**
( https://issues.intellectualsites.com/issue/PS-40 )

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
Won't be added
