### ISSUE TITLE
npc-cap flag request

### ISSUE THREAD

**Issue by cnMolean** [IntellectualSites/PlotSquaredSuggestions#130]
**PlotSquared Feature Suggestion:**
Add "npc-cap" flag that can limit the villager amount. The villagers could cause unbelievable lag since 1.14. I want that players raise other animals instead of too many lag causer -- villagers. I think it's useful for 1.14+ servers.

**How should it be implemented?**
Just like "mob-cap" or "animal-cap". Cancel villager's spawning if the amount of villager in the plot reached npc-cap. 

**Additional context**
Nothing.

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
Villagers are covered by the mob-cap and entity-cap flag.
