### ISSUE TITLE
more economy features (e.g. rent)

### ISSUE THREAD

**Issue by kamileks999** [IntellectualSites/PlotSquaredSuggestions#132]
**PlotSquared Feature Suggestion:**
Hello,
can you add option to rent a plot for a time? It can be useful for plots near spawn, which are usually abandoned. The players will have to pay daily/weekly/monthly fee for having access to plot and after they won't pay, the plot will be cleared.

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
I think for economy systems like this an add-one would be useful.

For a real-life / citybuild server the follow functions are useful:

- time-limitation
- rent
- dynamic princes depended on the plot-size / position / blocks in the plot etc.
- automatism after a term of validity

But it's not the target of the main plugin, I think.

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/61

**Comment by RedstoneFuture** [comment]
I hope it's okay that use this ticket as collection for economy feature-request. I think it's the same question in all cases: the target of the main plugin as plotsystem.

**Comment by DevJoey** [comment]
No pls no. PlotSquared is not a rent system. It can be added with an addon. No need to implement lot of useless features in one plugin.

**Comment by AeSix** [comment]
> No pls no. PlotSquared is not a rent system. It can be added with an addon. No need to implement lot of useless features in one plugin.

This.
