### ISSUE TITLE
Show all Owners of a Plot in the Title

### ISSUE THREAD

**Issue by xManInWhitex** [IntellectualSites/PlotSquaredSuggestions#140]
**PlotSquared Feature Suggestion:**
If some different players are merging their plots, they are registered as multiple owners at the /p i info board.
The Placeholder %s in the language file should shows all owners, comma separated.

**How should it be implemented?**
A true / false variable could be built into the config file, with which one we can set whether only one owner or all owners of a plot should be displayed in %s/title. (Or an additional placeholder)

**Additional context**
Issue where I thought that only one owner is shown was a bug:
https://issues.intellectualsites.com/issue/PS-146?project=PS

![image](https://user-images.githubusercontent.com/54602589/94486885-57aa1b00-01e0-11eb-9dc5-28ab5ac4967d.png)

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
Multi-Owner is more a bug as a full-integeraded feature.

Try the `%plotsquared_currentplot_owner%` [placeholder](https://wiki.intellectualsites.com/en/plotsquared/placeholders) for the titel-string - maybe it works better than the `%s` argument.

**Comment by xManInWhitex** [comment]
If I'm using %plotsquared_currentplot_owner% it will printed as %plotsquared_currentplot_owner%.. There are no names..
PlaceholderAPI is turned on in the config? What I have to do to use the Placeholders on titles?

**Comment by RedstoneFuture** [comment]
Poly ownership should not be allowed (currently it's only a bug) so it's not needed to support a multi-owner list in the titel and `%s` is enough to display one owner, sorry.

Poly ownership coming up with too many problems and it's not supported at this time.
