### ISSUE TITLE
Seperating No permission messages

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquaredSuggestions#142]
**PlotSquared Feature Suggestion:**

It would be nice if the command no permission message and the build on road permission messages gets seperated. So i can translate plot quared better. I would like to be able to remove the permission message, if the player builds. So he get not be spammed. But for the command no permission i will have a simple. "Yo do not have the permission to execute this command".
It would be nice if the no permission messages gets seperated.

**How should it be implemented?**

Folowing keys in the language section.
command-noperm: "You need the permission %s to use this command!"
build-road-noperm: "You cant build on the road."
interact-noperm: "You cant interact with that."
pvp-noperm: "You have no permission for PVP here."
pve-noperm: "You have no permission for PVE here."

**Additional context**

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by DevJoey** [comment]
why Declined? it is a useful feature

**Comment by dordsor21** [comment]
There are hundreds of permissions that P2 uses - this would take a massive amount of time to do, and increase the size of translations files massively. It's not a feature anyone else has requested, so the effort and drawbacks required are not worth it for us.
