### ISSUE TITLE
signs, guis

### ISSUE THREAD

**Issue by cicatrice74** [IntellectualSites/PlotSquaredSuggestions#145]
Lately a system has entered the scene that allows minecraft owners for mobile to be able to enter the java servers, but with that version it is very difficult to manage the commands in the chat, it would be nice to have the signs in order to be more controller-friendly or touch friendly

**Comment by cicatrice74** [comment]
Please insert the possibility to show how many likes a plot has received

**Comment by AeSix** [comment]
first: two suggestions, two tickets.

Second: supporting. bedrock clients on java servers may not be possible for P2 as there is no way to identify the type of client connected.

As far as the 'likes' - you can probably dp this already with placeholders & a sign pkugin able to display placeholders.

**Comment by RedstoneFuture** [comment]
I agree with AeSix comment. Use a GUI plugin for this problem. It is more user-friendly as a sign wall, I think. You need a GUI for your complete server, if you have this mobile problem. So it's not needed to create an own system only for PS.
