### ISSUE TITLE
New Flag: "mob-damage"

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquaredSuggestions#146]
**PlotSquared Feature Suggestion:**
This is a small feature request I would like to see implemented. It is an additional boolean flag called "mob-damage" which will determine whether or not players can be hurt my mobs. It would be pretty much the same as the WorldGuard flag, also called "mob-damage".

On my server, I allow mobs on plots. The issue I have is that mobs that can fire projectiles (i.e. Blazes) are able to hurt players that are on the road nearby. I know there's an "invincible" flag I can use to prevent this, but I don't want players to be totally invincible - I just want them to not be able to be damaged by mobs from someone else's plot. I also don't want to set the "mob-damage" flag of WorldGuard to false in the "global" region, because I want players to be able to take damage from mobs in their own plot. I've also tried using the "pve" flag and setting it to false on the road, but this doesn't fix the issue.

I'm sure other servers would benefit from this feature being added too.

**How should it be implemented?**
It would just be an additional flag that can be set. Its functionality is described above.

**Additional context**
N/A

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
PVE: player vs. player + player vs. environment + mobs vs. mobs

PVP: player vs. player

So the PVE flag is the right flag for this problem. Please check your specified situations and report a bug if you find a problem with the PVE flag. I've tested the PVE flag for a longer time, and it works fine for me.


`I also don't want to set the "mob-damage" flag of WorldGuard to false in the "global" region [...]`
In every case down't use WorldGuard flags for your plotworld, please.

**Comment by TheosisOfficial** [comment]
> PVE: player vs. entities + player vs. environment + entities vs. entities
> 
> PVP: player vs. player
> 
> So the PVE flag is the right flag for this problem. Please check your specified situations and report a bug if you find a problem with the PVE flag. I've tested the PVE flag for a longer time, and it works fine for me.
> 
> `I also don't want to set the "mob-damage" flag of WorldGuard to false in the "global" region [...]`
> In every case down't use WorldGuard flags for your plotworld, please.

I've just tested the PVE flag on the road more thoroughly, and it seems as it _only_ prevents players from being able to hurt mobs, but the mobs can still hurt players. The flag seems to work fine on plots though.

I did this testing with no plugins other than PlotSquared, WorldEdit and Hyperverse to make sure no other plugins could potentially be interfering. Do you think I should make a bug report on this?

**Comment by RedstoneFuture** [comment]
Ah, ok. On roads, I've not tested the flag. I'm not sure if the road-flag system are completed. So long you don't need to write a new bug-report. It's ok, thx.

**Comment by TheosisOfficial** [comment]
> Ah, ok. On roads, I've not tested the flag. I'm not sure if the road-flag system are completed. So long you don't need to write a new bug-report. It's ok, thx.

No problem. Is there any ETA on when the road-flag system will be completed?

**Comment by RedstoneFuture** [comment]
No, sorry. The devs work on many features / issues. The plugin is very big, so it's not sure when it will be completed.
