### ISSUE TITLE
Intercepting plot chat

### ISSUE THREAD

**Issue by SrLeojaco** [IntellectualSites/PlotSquaredSuggestions#15]
If i cancel asyncplayerchatevent plot chat is still being shown. For antispam and other plugins that rely on chat would be good to be able to intercept the event before it is sent to plot chat

**Comment by N0tMyFaultOG** [comment]
Added in https://github.com/IntellectualSites/PlotSquared/pull/2142

**Comment by SrLeojaco** [comment]
yep
