### ISSUE TITLE
Command for fixing roads Regen only the road iam stand on

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquaredSuggestions#151]
**PlotSquared Feature Suggestion:**

**How should it be implemented?**

If i merge a players plot and i want to rezize that merge (Take plots) i use /p unlink false and then i merge the plots again with /p merge false
but some times the road gets broken, so i have to fix the road with worldedit. it would be nice if there is a command /plot fixroad which fixed the road im standing on. regenerates only that piece of road.

**Additional context**

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
`/plot debugroadregen` regenerates parts of the road.
