### ISSUE TITLE
Flag for limiting block-types in worlds.yml

### ISSUE THREAD

**Issue by Villmarksjenta** [IntellectualSites/PlotSquaredSuggestions#156]
**PlotSquared Feature Suggestion:**

Add a a flag you can add in worlds.yml which limits certain block types. For example PISTON: 5 creates a limit of 5 pistons within each plot. I am aware that you can use chunk-prosessor to limit tile entities etc. but unfortunately pistons (and some other blocks) does not go within that category.

**How should it be implemented?**

You can for example be able to to something like this:
flags:
  block-limit:
    - PISTON: 5
    - OBSERVER: 3

**Additional context**

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/136

"This is out of the scope of PlotSquared."

**Comment by RedstoneFuture** [comment]
Unless that you only need a config option for all worlds, an entity cap /counter isn't the same as a block cap. You need a live counter for all blocks in your plot with using of the FAWE API. This should need a lot of performance, I think. I suggest: Develope a seperately add-on for this problem.

**Comment by Villmarksjenta** [comment]
Ok :/ Thanks for replying :)
