### ISSUE TITLE
RegenAllRoads

### ISSUE THREAD

**Issue by WalrusSlayer** [IntellectualSites/PlotSquaredSuggestions#158]
**PlotSquared Feature Suggestion:**
RegenAllRoads for schematics doesn't work:
**How should it be implemented?**

Fixing it would be a great new feature!
**Additional context**

![image](https://user-images.githubusercontent.com/40503028/107297550-99c25380-6a41-11eb-9587-6b91d04ea80e.png)

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
Please use https://issues.intellectualsites.com für Bug-Reports.
