### ISSUE TITLE
Commands only in plot

### ISSUE THREAD

**Issue by Gamemap** [IntellectualSites/PlotSquaredSuggestions#159]
**PlotSquared Feature Suggestion:**
Add the ability to use commands and structure blocks in the plot when they are not /op (not over the plot area, so no griefing is possible)

**How should it be implemented?
If a command/structure block is out of bounds, an error message appears.

**Additional context**.

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [] I made sure my suggestion is useful for the majority of PlotSquared users

- [x] I think my suggestion is useful for the majority of PlotSquared users

**Comment by NotMyFault** [comment]
Won't be added.

**Comment by RedstoneFuture** [comment]
@Gamemap You can develop an extension for your permission system (e.g. [Luckperms Extensions](https://luckperms.net/wiki/Extensions)) with using of the PlotSquared API to restrict your server-features / command based on the plots. But I think a restriction system like that isn't the focus of PlotSquared. Additionally, you have to restrict proxy commands too, and this isn't impossible with a bukkit plugin.

**Comment by Gamemap** [comment]
Thank you for this explanation.

Unfortunately I don't know how to program something like this and don't have enough time to learn it now. 
So I can understand the rejection.
