### ISSUE TITLE
/plot like system

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/PlotSquaredSuggestions#19]
Commands
/plot like
/plot unlike
/plot likes

%likes% placeholder in /plot info

(there is no rating placeholder)

**Comment by N0tMyFaultOG** [comment]
See https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/3

**Comment by tspierer2** [comment]
> See #3

I saw, how would I add a placeholder for likes
