### ISSUE TITLE
Separated Plotworlds

### ISSUE THREAD

**Issue by smallestchild** [IntellectualSites/PlotSquaredSuggestions#2]
Hello. I run a multiverse server that has multiple plotworlds, including survival plotworlds. When we set it up, we used the plugin PlotMe, but due to it being discontinued, we want to switch to PlotSquared. However, I haven't been able to find any documentation about separate plotworlds besides an issue on PlotSquared which essentially stated that it doesn't exist (https://github.com/IntellectualSites/PlotSquared/issues/1755). 

The survival plotworlds are very much separate from their creative counterparts, and we're afraid of confusion that might happen as a result of players running /plot h and ending up in Creative, especially if there aren't staff online to teach them about specifying world. 

Is it possible for Separate Plotworlds to be integrated into PlotSquared, or any sort of feature where a player in a specific world will only teleport to plots in that world unless they specify world?

**Comment by boy0001** [comment]
This is already implemented. You can talk with us on discord if you get stuck setting it up:
https://discord.gg/ngZCzbU

Installation instructions:
https://github.com/IntellectualSites/PlotSquared/wiki/Installation

**Comment by smallestchild** [comment]
Okay, thank you. I couldn't find anything directly referencing it, so I probably will reach out in the future.
