### ISSUE TITLE
Plot Admin

### ISSUE THREAD

**Issue by UltimateGamer200** [IntellectualSites/PlotSquaredSuggestions#20]
Maybe add a feature where plot owners can add plot admins/co-owners where they can do almost everything the owner can. Examples:
- Adding/Removing Players.
- Kicking/Banning Players.

**Comment by MattBDev** [comment]
The categories of trusted, helpers, and denied should be enough where this isn't needed. If these options aren't enough then an add-on would be more appropriate.
