### ISSUE TITLE
"fly" flag permission override 

### ISSUE THREAD

**Issue by Matocolotoe** [IntellectualSites/PlotSquaredSuggestions#23]
**Debug paste link** 
https://hastebin.com/fusuluruzu

**Description of the problem** 
I would like to suggest something to allow automatically or with an option (in a config file, in a command...) at least plot owners (and if it's possible trusted and added players to the plot) to fly even if the `fly` flag is set to false.

**How to replicate** 
Toggle fly mode in a plot where the `fly` flag is set to false

**Checklist**
- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)]
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Matocolotoe** [comment]
ikr i checked the code because i tried to do that myself but thought it would be better to suggest it to everyone ^^

**Comment by Matocolotoe** [comment]
any news on this ?

**Comment by AeSix** [comment]
I'm not sure this is a feature that will ever be implemented as your request would blatantly bypass a feature doing as designed.

Likewise, having an "admin" perm to allow groups or players to bypass the flight restriction or to bypass flight restrictions for spectator mode would be something that does not blatantly bypass the working-as-designed function.

**Comment by Matocolotoe** [comment]
my request is to make plot members, trusted and not only owners not affected by the `fly` flag, I cannot set every member to a plot owner

**Comment by N0tMyFaultOG** [comment]
A good way would be exempting people added to the plot (or maybe just trusted) and add an override permission node to exempt certain groups.
