### ISSUE TITLE
Road Schematics Error

### ISSUE THREAD

**Issue by EnTIv** [IntellectualSites/PlotSquaredSuggestions#24]
Build:
![i a_ tm f26i 96 l1 4](https://user-images.githubusercontent.com/38716516/50253313-c875ae00-0424-11e9-8454-f6b5aa01130e.png)

Generate:
![msr jn30fvu 4 ict2 1qqv](https://user-images.githubusercontent.com/38716516/50253314-c875ae00-0424-11e9-9255-1825fa1a86c0.png)

PlotSquared (Version: PlotSquared-18.12.18-3be23a3-2055)
This server is running Paper version git-Paper-"684bd2ad" (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

No console error

Schematics:
[Schematics.zip](https://github.com/IntellectualSites/PlotSquaredSuggestions/files/2696791/Schematics.zip)

**Comment by Sauilitired** [comment]
Wrong project. But update to PlotSquared 4.
