### ISSUE TITLE
plot-list where I have permissions as trusted or as added user

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquaredSuggestions#27]
Do plotsquared have a function to list plots where I can build within as trusted or as added user?

**Comment by Sauilitired** [comment]
`/plot list shared`

**Comment by RedstoneFuture** [comment]
Ah, great! And how I get the plot where a specifically player is shared? I have problems with the syntax:

`/plot list <forsale|mine|shared|world|top|all|unowned|unknown|player|world|done|fuzzy <search...>> [#]`

The command `/plot list shared Nejael` or `/plot list Nejael shared` down't show this correctly plots.

**Comment by RedstoneFuture** [comment]
@Sauilitired
