### ISSUE TITLE
Plot like/dislike

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquaredSuggestions#3]
I'm aware that there is already a system for rating plots from 1-10. But I had an idea for a plot like/dislike system. For example players can use `/plot like` to like a plot and `/plot dislike` to dislike a plot.
Once the plot gained a like or dislike, you are able to see the amount of likes or dislikes on `/plot info` or via `/plot list likes` and `/plot list dislikes`.
This way players can simply show if they like or dislike a plot.

**Comment by boy0001** [comment]
Possible way to implement this is to hide the numeric rating, and consider 1/10 a dislike, and 10/10 a like. Then just alias `/plot like` and `/plot dislike` to those ratings.

**Comment by Sauilitired** [comment]
Implemented in version 4.
