### ISSUE TITLE
Stop generating blocks noone can see.

### ISSUE THREAD

**Issue by PixelNotFound** [IntellectualSites/PlotSquaredSuggestions#39]
PlotSquared generates blocks players can see. This will make their FPS go lower and the TPS go lower because the server has to send those blocks.
There are only pros with this no cons. Players get higher FPS because they dont have to render those blocks in that they wont see anyways, and the server doesnt have to send those to the client. I am talking about the blocks under the road for example. https://cdn.discordapp.com/attachments/344128265075556353/551743860879917056/2019-03-03_13.32.21.png

Please make the plugin just render the highest block on the road instead of all blocks under it that they wont see anyways but make their FPS go lower.

**Comment by Sauilitired** [comment]
The client doesn’t render blocks that aren’t visible. There would be no difference in FPS. What if a player were to dig in their plot, then there’d just be air? If you want this, set the wall filling to air. The server still sends the empty blocks to the player, as air blocks are blocks too 🤷‍♂️

**Comment by PixelNotFound** [comment]
@Sauilitired 
> The client doesn’t render blocks that aren’t visible. There would be no difference in FPS. What if a player were to dig in their plot, then there’d just be air? If you want this, set the wall filling to air. The server still sends the empty blocks to the player, as air blocks are blocks too 🤷‍♂️

In facts, a client does. Minecraft does nothing to dont render those blocks. So its best not to send those blocks.
And even if the client does hide those blocks, the server sends them. So it would make a diffrent for the server.

**Comment by dordsor21** [comment]
You clearly don't have much idea how this stuff works. This is not something we'll do because it will be in a negative impact to performance. Especially if every time a block is broken, we need to send block updates to not show air. It doesn't make any sense...
