### ISSUE TITLE
Suggestion or bug report of "/plot purge"

### ISSUE THREAD

**Issue by Weark** [IntellectualSites/PlotSquaredSuggestions#4]
I had reported a problem, which I'm not sure if this might have been a problem, since the command: "/plot purge world:plotworld unknown:true"
is removing the unknown owners but the constructions are getting on the plot, and I do not know how to solve remove all the thousands of buildings with unknown owners that have in my plotworld, I already tried to use auto clear to clean inactive plots, but it does not remove plots who are with unknown owners.

If the "/plot purge" command is bugged, please resolve.
If it is so anyway they could add:

Default: "/plot purge world:%world% area:%area% id:%id% owner:%owner% shared:%shared% unknown:[true|false]"

New: "/plot purge world:%world% area:%area% id:%id% owner:%owner% shared:%shared% unknown:[true|false] clear:[true|false]"

**Comment by Weark** [comment]
They should add a delay for cleaning each plot, as I have more than 16,000 plots with unknown owners and when I use the command to clean it crash the server, besides having the problem of not cleaning the constructions.

**Comment by SrLeojaco** [comment]
My tip is using plot purge and then setting a schematic of an empty plot when claiming new plots.

So... you clear your database, you keep the builldings but the player get's a new fresh plot when he uses /plot auto


I should also say that if you have a 100GB uncompresed (~32GB compressed) server like me, you'll keep that size.

**Comment by N0tMyFaultOG** [comment]
Implemented in https://github.com/IntellectualSites/PlotSquared/pull/2714/commits/baddc49e7e20fb4e44a9481cfbde2c7aa7246cf3
