### ISSUE TITLE
spawn area / spawn-plot ideas

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/PlotSquaredSuggestions#43]
There's several ideas for handling a spawn plot or merged plot. 

1. special owner name: 
   1. * (potentially used to specify any/all UUIDs, not a good choice in my opinion)
   2.  00000000-0000-0000-0000-000000000000 (nil UUID) which will disallow any/all players from access the plot as owner. 
***NOTE*** The UUID FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF should not be used as it may be interpreted as "any" UUID - which could be useful to a plot to allow any and all players to use, which is in opposition of protecting the spawn plot. 
2. plot flag:
   1. "spawn-plot" which would give anyone with plots.spawnplot.use permission to act as trusted
      * This should trigger a response to the admin to set no-expire as well
   2.  "hide-info" which would change the output of /p info:
      1. say there is no plot (which could be confusing)
      2. give no output at all (which could cause "HEY! It's broken!")
      3. send a configurable message as output (which could be nice, and could include 1, 2 and 4)
      4. tell the player they do not have permission to view the info
         * this would allow for giving a permission to admins to bypass the flag, which would allow for maintenance - adding/removing trusted, changing welcome/leave messages, etc.
3. Config file section of options to include:
   * owner - could be set to a real player name, or any UUID
   * members/trusted - used to give access to staff
   * flags (including no-expire, hide-info, etc)
   * plot ID(s), if multiple IDs, merge all adjacent plots
   * merged - default to true, but set to false to override merging behavior
   * info:
      * true - would send standard info
      * false - would send "You are in a spawn plot"
      * custom - would use customeinfo (below)
      * perms - would send "You are in a spawn plot" to anyone without the perm, and full info to anyone who has the perm
   * custominfo - used only if "info: custom" is set above, could be set to up to 10 lines of wrapped text
4. Provide a configurable area that is not handled by p2 at all, allowing WorldGuard, etc to handle protections.  This should be specified by number of plots radius (1 being each plot around 0,0, so a total of 4 plots - 2 would be 16 plots of space) This area should be outlined with the road as the boundary.  I say this should be defined by number of plots instead of number of blocks so that there are no broken/partial plots surrounding the area.  This would be the simplest to administer, but may be the most difficult to impliment. 

These are all just ideas, some of which were brought up in discord.

**Comment by Sauilitired** [comment]
hide-info flag has been implemented

**Comment by Sauilitired** [comment]
server-plot flag implemented

**Comment by Sauilitired** [comment]
4 is not going to be implemented, as it'd require a lot of changes. You can create a WorldGuard region within (or wherever, really) a plot, and let WG handle certain flags. 

Maybe create a mega plot, add everyone and then use WorldGuard for protection? That should work. You can create a new ticket for this, if this is something you want to discuss further.

**Comment by AeSix** [comment]
Nah, it was just one of 4 main ideas for producing a similar result :)
