### ISSUE TITLE
Changing language of /plot help

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [IntellectualSites/PlotSquaredSuggestions#45]
Hi,
now its possible to change language of every command including /plot and all further combinantions, so plugin is more suitable for younger players, who dont understand english.
There is one exception - its not possible to change all /plot help commands and whats describing them. it would be awesome to change all of them - including help, so insted /p help claiming woulg be (in polish) /d pomoc przejmowanie

**Comment by MattBDev** [comment]
I believe this is currently being worked on with the new command system. 😁

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/35

**Comment by Sauilitired** [comment]
This has already been implemented.
