### ISSUE TITLE
New script to set the border of claimed plots

### ISSUE THREAD

**Issue by steve4744** [IntellectualSites/PlotSquaredSuggestions#46]
After running 'regenallroads' the borders of claimed plots get reset to the same block as unclaimed plots. In the same way that signs on claimed plots can be re-added with script _addsigns.js_, this script will reset the borders of claimed plots to whatever is block specified as `wall.block_claimed` in _worlds.yml_.

In addition, it could also be used with the new 1.14 slabs to change the look of existing plot worlds with minimum effort.

`plot debugexec run setborders.js <plotworld>`

```
/*
This script will update the border walls of claimed plots
Run on console: plot debugexec run setborders.js <plotworld>
*/
if (PS.hasPlotArea("%s0")) {
    var plots = PS.sortPlotsByTemp(PS.getPlots());
    for (var i = 0; i < plots.size(); i++) {
        var plot = plots.get(i);
        var world = plot.getWorldName();
        if ("%s0" === world) {
            if (!plot.isMerged() || !plot.getMerged(0)) {
                plot.setComponent("border", PS.worlds.getString("worlds." + world + ".wall.block_claimed"));
                PS.class.static.log('&cSetting border for ' + plot + " to " + PS.worlds.getString("worlds." + world + ".wall.block_claimed"));
            }
        }
    java.lang.Thread.sleep(10);
    } 
}
else {
    PS.class.static.log("Usage: plot debugexec run setborders.js <plotworld>");
}
```

**Comment by N0tMyFaultOG** [comment]
If you want to add that specific script, feel free to fork PlotSquared and make a quick pr.
