### ISSUE TITLE
Plotsquared new command

### ISSUE THREAD

**Issue by AbelMG** [IntellectualSites/PlotSquaredSuggestions#47]
The command was /plot admin paste (user) (plot number) (new schematic) (-a, -s, -o, or nothing if you want it to be fully pasted.) It would be a good feature to add plots upgrades or automatically given plots. I’ve always thought about this command and thought plotsquared had one like this too! But i discovered it doesn’t so im suggesting it!

**Comment by RedstoneFuture** [comment]
What is the idea behind the command? To paste a schematic in a plot without to stand in here?

**Comment by N0tMyFaultOG** [comment]
What would the purpose of it be? You can already paste schematics to plots.
