### ISSUE TITLE
Permission Split :  plots.merge

### ISSUE THREAD

**Issue by SplinterCurty** [IntellectualSites/PlotSquaredSuggestions#5]
Division of the permission plots.merge in 2 Perm. At the moment you can use all the commands. It would be desirable to be able to give the users the opportunity to receive the roads while merging.
Example of a new permission
plots.mergeroads.

Is this sufficient as an info or do you need more?
Greets Splinter

**Comment by Serial1990** [comment]
Push... Kann doch nicht so lange dauern... :/
