### ISSUE TITLE
Adding Polish Language

### ISSUE THREAD

**Issue by Nacioszeczek** [IntellectualSites/PlotSquaredSuggestions#50]
Hello!

Your Plugin is awesome and I really love it, but my suggestion is, that many Polish servers use this Plugin mostly for Creative Server Mode which a lot of kids play, who are too young to understand English therefore I could make a Polish language version for each release if you would like me to.
Thanks!

**Comment by MattBDev** [comment]
We accept PR's on our repository. If we can't speak or read the language it's difficult for us to translate. Please feel free to submit a translation file to us on our main repo.
