### ISSUE TITLE
add "/plot regenallplots"

### ISSUE THREAD

**Issue by skilledpt** [IntellectualSites/PlotSquaredSuggestions#51]
Add option like there is for generate roads but for plots like:

/plot createrplotschematic
/plot regenallplots <world> [height]

So we can do something like this:

![image](https://user-images.githubusercontent.com/24494725/62009669-cbbede00-b159-11e9-8612-17c579fdf5ec.png)

**Comment by RedstoneFuture** [comment]
1. currently command = "/plot schematic save"
https://github.com/IntellectualSites/PlotSquared/wiki/Schematic-on-Claim

2. mmh .. maybe it works with "/regenallroad" too, if you have a valid plot schematic and have disabled the "on_claim" part in the world.yaml .

**Comment by N0tMyFaultOG** [comment]
That can be achieved by pregenerating your world based on a certain pattern. There are several worldborder plugins available which achieve the desired behavior.

**Comment by RedstoneFuture** [comment]
I think you mean "world generation plugins"? Yes, this can help.
