### ISSUE TITLE
Other Can't Buy in Shop

### ISSUE THREAD

**Issue by VenomHZ** [IntellectualSites/PlotSquaredSuggestions#54]
Im using QuickShop Reremake plugin and people that i dont trust cant use the sign. It said "[P2] Have an admin set the flag: use/break"

**Comment by N0tMyFaultOG** [comment]
Go to `/plugins/PlotSquared/config/worlds.yml` and set the following variable:
```yaml
    flags:
      use: chest
```
Or whatever item it uses, but it seems it uses chests.
