### ISSUE TITLE
option to prevent falling/flying entities from exiting plot

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/PlotSquaredSuggestions#55]
I don't know how feasible this would be to add to P2 without a heavy load on resources, however:
Adding the ability to prevent flying and falling entities (tnt, armor stands, exploded blocks, etc) from exiting the plot could be needed.

This is in contrast to killing road entities, in which entities in the road areas are culled. 

Again, the checks for this may be considered too intensive to implement, and an option to enable it should be added, with it disabled by default - and disabled in code if kill road entities is enabled.

**Comment by MattBDev** [comment]
This should already be added. Flying sand is blocked and so should other blocks (unless the code is only looking for sand but i can't remember )

**Comment by RedstoneFuture** [comment]
I suggested a kill-road-entities flag before a long time ago, because fire_charge  aren't remove If he fly over the plots: https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/26

**Comment by N0tMyFaultOG** [comment]
Can be added if https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/26 is added.
