### ISSUE TITLE
Confirmation for set plot components

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquaredSuggestions#6]
A confirmation for the commands below would be neat since you cannot undo them.

- `/plot set main <block>`
- `/plot set all <block>`
- `/plot set air <block>`
- `/plot set floor <block>`
- `/plot set outline <block>`

**Comment by Sauilitired** [comment]
Merging #18 with this one:

> /plot generatebiome should also have /plot confirm option, just like /plot clear does, because it basically resets your plot without warning and ignorant players who are just experimenting with this command on my server could accidentally delete their plots.
thanks!

**Comment by Sauilitired** [comment]
We are rewriting the command system, so this can easily be implemented in v4.

**Comment by Sauilitired** [comment]
They can now be undone if using the automatic backup system. I don't know if we need additional confirmations on top of that?

**Comment by N0tMyFaultOG** [comment]
Nope, that seems fine.
