### ISSUE TITLE
Greeting as a action bar text.

### ISSUE THREAD

**Issue by RemyyB** [IntellectualSites/PlotSquaredSuggestions#60]
Hi there, I have a suggestion, when you create a greeting for your plot, the greeting itself is in the chat, maybe this could be done in the 'action bar', this way it isn't going to spam you as you sometimes go in and out your plot :)

Of course this should also be applied to farewell

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/25

I think the greeting is by default longer than the action bar width.
