### ISSUE TITLE
[Suggestion] More Message Translation

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquaredSuggestions#66]
Hey, I have only 2 Suggestions.

1. Command-Usages translatable
2. Command Description Translatable
3. Commandcategories Translatable
4. The Message The flag must be a boolean translatable

It would be very nice. I dont know how i can make suggestions in this case i posted it here. Sorry if this is the wrong location. If it is the wrong location, it would be nice, if you send me the right place for suggestions.

**Comment by N0tMyFaultOG** [comment]
A link to the suggestion repo is in the template you kindly deleted (and most likely did not even read).
Also, what do you mean by 1, 2 and 3? Add an example as well please.

**Comment by RedstoneFuture** [comment]
1. -> "/PlotSquared/config/commands.yml"
2. -> "/PlotSquared/config/commands.yml"
3. -> "PlotSquared/translations/PlotSquared.use_THIS.yml" -> category

**Comment by N0tMyFaultOG** [comment]
> 1. -> "/PlotSquared/config/commands.yml" (command -> "usage")
> 2. -> "/PlotSquared/config/commands.yml" (command -> "description")
> 3. -> "PlotSquared/translations/PlotSquared.use_THIS.yml" -> category

For 4 I already pushed some changes, but I'm not sure what he was referring to, since commands are translatable. Maybe we forgot something, dunno

**Comment by RedstoneFuture** [comment]
> 
> 
> > 1. -> "/PlotSquared/config/commands.yml" (command -> "usage")
> > 2. -> "/PlotSquared/config/commands.yml" (command -> "description")
> > 3. -> "PlotSquared/translations/PlotSquared.use_THIS.yml" -> category
> 
> For 4 I already pushed some changes, but I'm not sure what he was referring to, since commands are translatable. Maybe we forgot something, dunno

4. = syntax error at flag command with a wrong argument linke: "/p flag set hide wwwwww"
