### ISSUE TITLE
Create single plots, or clusters with W.E Wand (player creation support included?)

### ISSUE THREAD

**Issue by partridge420x** [IntellectualSites/PlotSquaredSuggestions#74]
**PlotSquared Feature Suggestion:**

Overall goal~
 The overall feature i am suggesting is to streamline, and make it overall easier to make clusters/single plots in vanilla generated worlds using world edit's wand 

-with configuration players can make their own plots in vanilla land
  * could be achieved by doing the following

     -configuration per size, (skim through this for in depth example)
     https://github.com/espidev/ProtectionStones/wiki/Configuration

      -configuration to how big plots can be (ie. 8 blocks from corner to corner)
people on servers can sell/gain "permission vouchers" by voting/selling in shop. where if you use it, you gain the permission (timed/permanent) to make the plot based on size (read next paragraph)

      - permissions for accessing / creating each different created config limit (ie.
      (plot/cluster).createsize.(8-16-32 etc,) if player had multiple groups with the same perm, but conflicting sizes, highest size would take priority (or lowest set global config?) 
  
      - select area with wand, if size is within limits of config allow next step of creation, 
       else say your selection is to large, please retry

(please comment if you have more ideas regarding this)

**How should it be implemented?**
Players / admins would receive perms to //wand, from there type the command to create an area, (single, or cluster) (shorthand command rewrite refer to additional context content), It will then prompt you to select your area that you would like to use for your plot/cluster using the wand
when selection has been made, type a command (ie. /(plot.cluster) wandconfirm), if it doesn't collide with other claims/regions or error out in other ways,  it would then teleport them to the edge like normal, plot/cluster made

**Additional context**
additionally separate the command to create a world, and create a plot/cluster
/Plot area create <Single/Cluster> (plot/cluster name)
/Plot CreateWorld (World name) type=1 terrain=? ＜modifiers＞

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
-I made sure my suggestion does not exist yet ||  It does exist, but it is a tad bit confusing, 
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
You can create single plots by setting up clusters and areas.
