### ISSUE TITLE
World export/import (and backups)

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/PlotSquaredSuggestions#75]
**PlotSquared Feature Suggestion:**

a way for an owner to export and import worlds, either all at once, or specific worlds. 
This could be done with /p export [<world>[,<world>]]
where no args would export all worlds, or specify a world, or a (comma separated) list of worlds 
This would copy ALL of the data needed to re-import the world to another server, including but maybe not limited to:
PlotSquare config file (just the section pertaining to the world(s))
world region data files
bukkit.yml config section (perhaps not needed?)
SQL/db data for the world

**How should it be implemented?**

On export, the appropriate files/data will be saved in a simulated directory structure and archived (zlib?) with no compression (no point to try to compress anything, the user can do that later)
This would create a single file which will be saved in plugins/PlotSquared/exported  named as
<world-name>.<iso-date>.plotsquared.export
(iso date being yyyymmddhhmm,  with a dash-separate iteration number (if multiple world saves happen at the same time)

This will give a file which the admin/owner can move to another server, or use as backups, or to "close down" a seasonal world, for example.

On import, the file will reside in the import target server's plugins/PlotSquared/exported folder
The admin would then run ```/p import``` followed by a `tab` to see a list of possible imports, with a full filename required for import. 

The world would be copied into place, the config files updated, and the SQL/db data inserted as needed.  Sanity checks should be made to ensure that there is no naming collisions, and that UUIDs are in the same mode (online/offline), a halt error given and process stopped (There's no sane way to handle offline UUIDs on a server using online UUIDs (or vice-versa) A second arg could be created "nouuids" which would forgo plot ownership insertions. 

**Additional context**

As stated, this could be used for a variety of reasons, from backups to seasonal worlds, to moving completed project worlds into production servers, etc.

Perhaps this could be done as a PS addon instead of core functionality. 

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by boy0001** [comment]
The plot template command is for exporting/importing the settings + schematics. It doesn't copy the map though.

**Comment by AeSix** [comment]
Right, which the suggestion is for a full and complete export, not just the template :)

**Comment by N0tMyFaultOG** [comment]
That can be achieved by having some knowledge of server administration.

**Comment by AeSix** [comment]
Wow. 
You really didn't have to be so rude.   It's a suggestion to make life easier for admins.  Not a "OMG! I don't know how to do shit! DO THIS FOR ME"
