### ISSUE TITLE
placeholder for "/plot info" to show the plot-creation date

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquaredSuggestions#77]
**PlotSquared Feature Suggestion:**
With a information when a plot was claimed (in form of a date) the staff can faster moderate the plots: If a plot is to young we wouldn't delete empty plots. But we moderate it manually and down't use the auto-clear function of plotsquared.

**How should it be implemented?**
- new placeholder for /p info
- maybe new command like "/p time" to show the claim-date

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
Plot creation dates are stored as time stamp, we would need to convert them to something human readable first.
