### ISSUE TITLE
Message after /plot regenallroads is succeed

### ISSUE THREAD

**Issue by jordi2010** [IntellectualSites/PlotSquaredSuggestions#78]
**PlotSquared Feature Suggestion:**

When execute the command `/plot regenallroads <world>` it can take a while. It would be usefull to see a message when the regenerating of the roads is done.

**How should it be implemented?**

Just a short message in the console or for the person who executed the command that regenerating of the roads is succeed.

**Additional context**

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by dordsor21** [comment]
This was already a thing, however, it was a debug message. Changed to a normal log.
