### ISSUE TITLE
Use bukkit.yml to register plot generator.

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquaredSuggestions#82]
**PlotSquared Feature Suggestion:**

If you create a new plotworld, PlotSquared should register the world at the bukkit.yml.
If people are not using MultiVerse-Core, the owner need to make that entry manually.
Additionally to that, we might want to add a `/plot tpworld <name>` command to teleport across (plot) worlds without the usage of a third party plugin.

**How should it be implemented?**
Described above.

**Additional context**
/

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by gp-Airee** [comment]
Don't edit my server config files.

**Comment by jokbon** [comment]
During plotsquared setup plugin shoud ask.
Do you want us to add your world entry to bukkit.yml ? Multiverse users don't require this step.

**Comment by N0tMyFaultOG** [comment]
Implemented in [PlotSquared v5](https://www.spigotmc.org/resources/77506/)

> Do you want us to add your world entry to bukkit.yml ? Multiverse users don't require this step.

Yes, because Multiverse acts as world management software here and handles it. But if you don't run Multiverse or any world management software, you need to add it yourself, which is just a tedious step, so we got you covered here.
