### ISSUE TITLE
Add a message if a flag cap has been hit

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquaredSuggestions#83]
**PlotSquared Feature Suggestion:**
I think we should add a message telling the player if a cap has been reached. E.g. global flag `entity-cap` is set to 50 and a plot hit the limit, the user might not know about it, because it cancels the task silently. I've seen a few cases where the current behavior results in confusion to players and server owners.

**How should it be implemented?**
No big warning required, just a simple message letting the user know about it.

**Additional context**
/

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by Sauilitired** [comment]
no

**Comment by N0tMyFaultOG** [comment]
yes

**Comment by Sauilitired** [comment]
how would that work? would we send it every time something attempts to spawn? or like once?

**Comment by N0tMyFaultOG** [comment]
If a player tries to build on a plot he has no access to it doesn't tell them every time they try to place a block. Only if they change their interaction iirc. But having no message isn't very ideal, because it can be interpreted as bug/issue on the server, yet it's just p2 cancelling the event because someone has hit the limit 🤷‍♂

**Comment by RedstoneFuture** [comment]
I think the problem are the amount of situations in there the player don't place the entity / vehicle / ... and at here we haven't a player as a target. If a big cube of sandblocks fall and will drop the sand-items, you can't send the owner this info-messages. At interactions like mob-spawn or item-drop it can work and are helpful too, but that need an own method, I think.
