### ISSUE TITLE
Schematics V2 for Roads/Plots

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquaredSuggestions#84]
Low priority, because it's a lot of work.

World generation uses the chunk data array, meaning this would need to be done by a populator. It would be best to use WorldEdit to set the blocks so we don't need to implement tile entity stuff ourselves.

**Comment by dordsor21** [comment]
https://github.com/IntellectualSites/PlotSquared/commit/f9bf576d2ed2f25cbe76f7dd0077a125dc13409e
