### ISSUE TITLE
Command to Forcibly Clear all Plots

### ISSUE THREAD

**Issue by InfinityAspire** [IntellectualSites/PlotSquaredSuggestions#89]
**PlotSquared Feature Suggestion:**
Title says it all.
Currently the purge command only unclaims plots, however this can cause issues as /p auto still treats them as 'in use' and places new players outside of them. It also seems the even when using the plot purge command with an SQL/MariaDB database, on restart the server likes to re-claim a lot of the purged plots.
If PS treated these as /p cleared plots, I don't believe this would be the case.

**How should it be implemented?**
Similar to the purge command makes the most sense.
Have PS treat every unclaimed plot as if an admin had just run /p clear while in it.

**Additional context**
N/A

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)] https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/4 is similar, however the solutions presented there don't help with the /p auto situation.

- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)

- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by N0tMyFaultOG** [comment]
Implemented in https://github.com/IntellectualSites/PlotSquared/pull/2714/commits/baddc49e7e20fb4e44a9481cfbde2c7aa7246cf3
