### ISSUE TITLE
Plot Protection from Expiry

### ISSUE THREAD

**Issue by UltimateGamer200** [IntellectualSites/PlotSquaredSuggestions#9]
Is there a way to protect plots from expiring? If so, how? If not, I would like to suggest that would be added because if someone wants to have an expiry system for their server for plots, they want to keep important plots safe. Thanks!

**Comment by boy0001** [comment]
The `keep` flag. 
`/plot flag set keep true`
`/plot flag set keep 5d35s` (5 days and 35 seconds)
