### ISSUE TITLE
Plot Api Question

### ISSUE THREAD

**Issue by Pyario** [IntellectualSites/PlotSquaredSuggestions#91]
**PlotSquared Feature Suggestion:**

All plots of a player with API in one gui? I'm not the best developer
Is that possible? Can I get an example?

**Additional context**

Plot Version:  4.489
Spigot-Version: 1.15.2

Best regards,

Pyario

**Comment by N0tMyFaultOG** [comment]
Wrong spot, join our discord server to ask questions regarding the API or take a look at the javadocs: https://ci.athion.net/job/PlotSquared-Releases/javadoc/
