### ISSUE TITLE
"use" or "place" flag but reversed (disallowing)

### ISSUE THREAD

**Issue by matbcvo** [IntellectualSites/PlotSquaredSuggestions#95]
**PlotSquared Feature Suggestion:**
There is "use" or "place" flag for allowing to place or use items that are listed, but there is no way to disallow placing/using items that are listed. For example I do not want to allow players place or use X item in all plots/plot world.

**How should it be implemented?**
Same way as implementing "use" or "place" flag.

**Additional context**
...

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
With `/p f s use <blocks>` you can define your plot-based list and overwrite the world-default value.

And if you use `/p f add use redstone_block` + `/p f add use sand` you can remove e.g. "sand" with: `/p f remove use sand`.

Why these commands don't enough?

**Comment by matbcvo** [comment]
I need to disallow players using/placing Furnance in plot world, so players can't use or place Furnance on their plot. How do you do that?

**Comment by Sauilitired** [comment]
You can’t use PlotSquared to limit what blocks plot owners may place. I’d recommend using WorldGuard with a global flag to achieve this, as it’s outside the scope of the PlotSquared flag system.
