### ISSUE TITLE
Block plotchat on specific plots

### ISSUE THREAD

**Issue by Langomatisch** [IntellectualSites/PlotSquaredSuggestions#96]
**PlotSquared Feature Suggestion:**

block the Plotchat on specific plots like a spawn or admin plots

**How should it be implemented?**

This feature could be implemented through a subcommand or a flag 

**Additional context**

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by dordsor21** [comment]
implemented in v5 714b8dad87285fb3873c7dd400004bbbe11e9dd7
