### ISSUE TITLE
Forced lowercase world name

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquaredSuggestions#99]
Spigot reverted the commit to force lowercase world names right after 1.13 was out, so we should remove it as well. Currently there is no need to keep it any longer since world names can be uppercased again.

**Comment by MattBDev** [comment]
I changed my mind again. I want all lowercase worldnames.

**Comment by N0tMyFaultOG** [comment]
🙅

**Comment by Sauilitired** [comment]
> I changed my mind again. I want all lowercase worldnames.

ok but y

**Comment by MattBDev** [comment]
I think we should also add passwords to the worlds.
